// TV show data parsed from your CSV
const tvShowsData = {
    "United Kingdom": [
        { title: "Fleabag", tags: [] },
        { title: "The Crown", tags: [] },
        { title: "Black Mirror", tags: [] },
        { title: "Humans", tags: [] },
        { title: "Orphan Black", tags: [] },
        { title: "Lovesick", tags: [] },
        { title: "You're the Worst", tags: ["therapist"] },
        { title: "Happy Valley", tags: [] },
        { title: "Killing Eve", tags: [] },
        { title: "Sherlock", tags: [] },
        { title: "Catastrophe", tags: ["gem"] },
        { title: "Derry Girls", tags: [] },
        { title: "Sick Note", tags: [] },
        { title: "Sex Education", tags: ["therapist"] },
        { title: "Years and Years", tags: ["gem"] },
        { title: "State of the Union", tags: ["therapist"] },
        { title: "After Life", tags: ["gem"] },
        { title: "Normal People", tags: ["gem", "book"] },
        { title: "I May Destroy You", tags: [] },
        { title: "The Duchess", tags: [] },
        { title: "This Way Up", tags: ["gem"] },
        { title: "Wanderlust", tags: ["therapist", "gem"] },
        { title: "Crashing", tags: ["gem"] },
        { title: "End of the Fucking World", tags: [] },
        { title: "Chewing Gum", tags: [] },
        { title: "Safe", tags: [] },
        { title: "My Mad Fat Diary", tags: [] },
        { title: "Downton Abbey", tags: [] },
        { title: "Broadchurch", tags: [] },
        { title: "Doctor Foster", tags: [] },
        { title: "We Are Lady Parts", tags: [] },
        { title: "The Pursuit of Love", tags: ["gem", "book"] },
        { title: "Landscapers", tags: [] },
        { title: "Starstruck", tags: [] },
        { title: "Bridgerton", tags: ["book"] },
        { title: "The Outlaws", tags: [] },
        { title: "Man Like Mobeen", tags: [] },
        { title: "Flowers", tags: [] },
        { title: "Mammals", tags: [] },
        { title: "Shantaram", tags: ["book"] },
        { title: "I hate Suzie", tags: ["gem"] },
        { title: "Bad Sisters", tags: [] },
        { title: "Ted Lasso", tags: ["therapist"] },
        { title: "Baby Reindeer", tags: [] },
        { title: "The Buccaneers", tags: ["book"] },
        { title: "Death and other Details", tags: ["gem"] },
        { title: "One Day", tags: ["book"] },
        { title: "Bodies", tags: [] },
        { title: "KAOS", tags: ["gem"] },
        { title: "Black Doves", tags: [] }
    ],
    "America - East": [
        { title: "Brooklyn Nine Nine", tags: [] },
        { title: "Broad City", tags: [] },
        { title: "High Maintainance", tags: [] },
        { title: "Girls", tags: [] },
        { title: "Community", tags: [] },
        { title: "Schitt's Creek", tags: [] },
        { title: "Search Party", tags: [] },
        { title: "Seinfeld", tags: [] },
        { title: "Unbreakable Kimmy Schmidt", tags: [] },
        { title: "The Politician", tags: [] },
        { title: "What we do in the Shadows", tags: [] },
        { title: "Barry", tags: ["gem"] },
        { title: "Corporate", tags: ["gem"] },
        { title: "Difficult People", tags: [] },
        { title: "This is Us", tags: [] },
        { title: "Orange is the New Black", tags: ["book"] },
        { title: "Friends from College", tags: [] },
        { title: "Suits", tags: [] },
        { title: "Easy", tags: ["gem"] },
        { title: "Recitfy", tags: [] },
        { title: "Life in Pieces", tags: ["gem"] },
        { title: "The Unicorn", tags: [] },
        { title: "The Other Two", tags: [] },
        { title: "Great News", tags: [] },
        { title: "Champions", tags: [] },
        { title: "Homecoming", tags: ["therapist"] },
        { title: "About a boy", tags: [] },
        { title: "Good Girls", tags: [] },
        { title: "How to get away with murder", tags: [] },
        { title: "13 Reasons Why", tags: ["therapist", "book"] },
        { title: "Gypsy", tags: ["therapist"] },
        { title: "You", tags: ["book"] },
        { title: "Younger", tags: [] },
        { title: "Sweet Magnolias", tags: ["book"] },
        { title: "Poker Face", tags: ["gem"] },
        { title: "The Curse", tags: [] },
        { title: "Mr and Mrs Smith", tags: [] },
        { title: "The Brothers Sun", tags: [] },
        { title: "The Diplomat", tags: [] },
        { title: "The Americans", tags: [] },
        { title: "Good Deed", tags: [] },
        { title: "Dying for sex", tags: [] },
        { title: "Deli Boys", tags: [] },
        { title: "Sex and the City", tags: ["book"] },
        { title: "The Affair", tags: [] },
        { title: "Mozart in the Jungle", tags: ["book"] },
        { title: "Mr Robot", tags: [] },
        { title: "Unreal", tags: [] },
        { title: "Top of the Lake", tags: [] },
        { title: "The Sinner", tags: ["book"] },
        { title: "The Flight Attendent", tags: ["book"] },
        { title: "The Morning Show", tags: ["book"] },
        { title: "Firefly Lane", tags: ["book"] },
        { title: "The Good Wife", tags: [] },
        { title: "The Good Fight", tags: [] },
        { title: "Happy Endings", tags: [] },
        { title: "The Chair", tags: [] },
        { title: "Dash & Lily", tags: ["book"] },
        { title: "Horace and Pete", tags: [] },
        { title: "Maid", tags: ["book"] },
        { title: "Severance", tags: [] },
        { title: "Peacemaker", tags: [] },
        { title: "Life & Beth", tags: ["gem"] },
        { title: "Mo", tags: [] },
        { title: "The Patient", tags: ["therapist"] },
        { title: "Blackbird", tags: [] },
        { title: "Shrinking", tags: ["therapist"] },
        { title: "Last of Us", tags: [] },
        { title: "Fleishman is in trouble", tags: ["book"] },
        { title: "Love & Death", tags: [] },
        { title: "The Last Thing he told me", tags: ["book"] },
        { title: "Who is Erin Carter", tags: [] },
        { title: "Beef", tags: ["gem"] },
        { title: "Expats", tags: ["book"] },
        { title: "The Bear", tags: [] },
        { title: "Lessons in Chemistry", tags: ["book"] },
        { title: "English Teacher", tags: [] },
        { title: "Nobody wants this", tags: [] },
        { title: "Only murders in the building", tags: [] },
        { title: "The Lincoln Lawyer", tags: ["book"] },
        { title: "Succession", tags: [] },
        { title: "The Perfect Couple", tags: ["book"] }
    ],
    "America - West": [
        { title: "Insecure", tags: [] },
        { title: "New Girl", tags: [] },
        { title: "Silicon Valley", tags: [] },
        { title: "Grace and Frankie", tags: [] },
        { title: "Crazy ex girlfriend", tags: ["therapist"] },
        { title: "Transparent", tags: [] },
        { title: "Jane the Virgin", tags: [] },
        { title: "Better things", tags: [] },
        { title: "Casual", tags: ["therapist"] },
        { title: "Alone Together", tags: [] },
        { title: "Hacks", tags: [] },
        { title: "Big Little Lies", tags: ["therapist", "book"] },
        { title: "Dead to Me", tags: [] },
        { title: "One Day at a Time", tags: [] },
        { title: "The Kominsky Method", tags: [] },
        { title: "Sorry for your Loss", tags: ["gem"] },
        { title: "The Last man on Earth", tags: [] },
        { title: "Love", tags: [] },
        { title: "Portlandia", tags: [] },
        { title: "Shrill", tags: ["book"] },
        { title: "Dave", tags: ["gem"] },
        { title: "Never have I ever", tags: [] },
        { title: "Awkward.", tags: [] },
        { title: "Dollface", tags: [] },
        { title: "Made for Love (2021)", tags: ["book"] },
        { title: "Nine Perfect Strangers", tags: ["book"] },
        { title: "White Lotus", tags: [] },
        { title: "Girlfriends' Guide to Divorce", tags: ["book"] },
        { title: "Afterparty", tags: ["gem"] },
        { title: "Pieces of her", tags: ["book"] },
        { title: "On the Verge (LA)", tags: [] },
        { title: "Home Economics", tags: [] },
        { title: "Euphoria", tags: ["therapist"] },
        { title: "Curb your enthusiasm", tags: [] }
    ],
    "America - One Season": [
        { title: "Enlightened", tags: ["gem"] },
        { title: "Little Fires Everywhere", tags: ["book"] },
        { title: "Strangers", tags: [] },
        { title: "Maniac", tags: [] },
        { title: "Modern Love", tags: ["book"] },
        { title: "No Tomorrow", tags: [] },
        { title: "Unbelievable", tags: ["book"] },
        { title: "Sharp Objects", tags: ["book"] },
        { title: "Mrs Fletcher", tags: ["book"] },
        { title: "Happyish", tags: [] },
        { title: "Unorthodox", tags: ["gem", "book"] },
        { title: "Don't Trust the B in Apt 23", tags: [] },
        { title: "SMILF", tags: [] },
        { title: "Togetherness", tags: [] },
        { title: "Terriers", tags: [] },
        { title: "Enlisted", tags: [] },
        { title: "Girlboss", tags: ["book"] },
        { title: "American Crime Story", tags: [] },
        { title: "Feud", tags: [] },
        { title: "Mindhunter", tags: ["book"] },
        { title: "I Love Dick", tags: ["gem", "book"] },
        { title: "The Undoing", tags: ["therapist", "book"] },
        { title: "United States of Tara", tags: [] },
        { title: "Olive Kitteridge", tags: ["book"] }
    ],
    "America - pre 2010": [
        { title: "Breaking Bad", tags: [] },
        { title: "Arrested development", tags: [] },
        { title: "Gilmore Girls", tags: [] },
        { title: "How I met your Mother", tags: [] },
        { title: "Scrubs", tags: [] },
        { title: "Gossip Girl", tags: [] },
        { title: "One Tree Hill", tags: [] },
        { title: "The OC", tags: [] },
        { title: "Psych", tags: [] },
        { title: "Lie to Me", tags: [] },
        { title: "Newsroom", tags: [] },
        { title: "Dexter", tags: [] },
        { title: "Friends", tags: [] },
        { title: "Grey's anatomy", tags: [] },
        { title: "Freaks and Geeks", tags: [] },
        { title: "Theat 70's Show", tags: [] },
        { title: "Modern Family", tags: [] },
        { title: "Big Bang Theory", tags: [] },
        { title: "Bones/Castle", tags: [] },
        { title: "Mad Men", tags: [] },
        { title: "In Treatment", tags: ["therapist"] }
    ],
    "Animated": [
        { title: "Bojack Horseman", tags: [] },
        { title: "Tuca and Bertie", tags: [] },
        { title: "Big Mouth", tags: [] }
    ],
    "Comedian Run": [
        { title: "The Mindy Project", tags: [] },
        { title: "Master of None", tags: [] },
        { title: "I'm Sorry", tags: ["gem"] },
        { title: "Ramy", tags: [] }
    ],
    "Disability focused": [
        { title: "Atypical", tags: ["therapist"] },
        { title: "Speechless", tags: [] },
        { title: "Special", tags: [] }
    ],
    "Supernatural / Period": [
        { title: "The Good Place", tags: [] },
        { title: "The Leftovers", tags: [] },
        { title: "Russian Doll", tags: [] },
        { title: "I am not Okay with this", tags: [] },
        { title: "Upload", tags: [] },
        { title: "Stranger Things", tags: [] },
        { title: "Marvelous Mrs Maisel", tags: [] },
        { title: "Handmaid's Tale", tags: [] },
        { title: "Glow", tags: [] },
        { title: "Masters of Sex", tags: [] },
        { title: "Dickinson", tags: [] },
        { title: "Sweet Tooth", tags: [] }
    ],
    "Located elsewhere": [
        { title: "Tyrant", tags: [] },        
        { title: "Four Weddings & a Funeral", tags: [] },
        { title: "The Great (hulu)", tags: [] },
        { title: "Ethos", tags: ["gem"] }
    ],
    "Europe": [
        { title: "Hook up Plan", tags: [] },
        { title: "Emily in Paris", tags: [] },
        { title: "Elite", tags: [] },
        { title: "Valeria", tags: [] },
        { title: "The Time it Takes", tags: ["gem"] },
        { title: "Call my Agent", tags: [] },
        { title: "Two Summers", tags: [] },
        { title: "Off the Hook (Détox)", tags: [] },
        { title: "Rita", tags: [] },
        { title: "Bonus Family", tags: ["gem"] },
        { title: "Love and Anarchy", tags: [] },
        { title: "Home for Christmas", tags: [] },
        { title: "Fallet", tags: [] }
    ],
  
    "Australia/Canada": [
        { title: "Please Like Me", tags: ["gem"] },
        { title: "Everything's gonna be okay", tags: ["gem"] },
        { title: "Working Moms", tags: ["therapist"] },
        { title: "Why are you like this?", tags: [] },
        { title: "the Letdown", tags: [] },
        { title: "Michael: Tuesdays & Thursdays", tags: [] },
        { title: "Wellmania", tags: [] },
        { title: "Aftertaste", tags: [] },
        { title: "Fisk", tags: [] },
        { title: "Deadloch", tags: [] },
        { title: "Heartbreak High (2022)", tags: [] },
        { title: "Murder mindfully (german)", tags: [] }
    ],
    "Indian": [
        { title: "Made in Heaven", tags: [] },
        { title: "Yeh Meri Family", tags: [] },
        { title: "Family Man", tags: [] },
        { title: "Panchayat", tags: ["gem"] },
        { title: "Mirzapur", tags: [] },
        { title: "Sacred Games", tags: [] },
        { title: "Pushpavalli", tags: [] },
        { title: "Breathe", tags: [] },
        { title: "Leila", tags: [] },
        { title: "Afsos", tags: [] },
        { title: "Patal Lok", tags: [] },
        { title: "Bandish Bandits", tags: [] },
        { title: "Masaba Masaba", tags: [] },
        { title: "Kota Factory", tags: [] },
        { title: "Taj Mahal 1989", tags: [] },
        { title: "Humorously Yours", tags: [] },
        { title: "Mismatched", tags: [] },
        { title: "A Suitable Boy", tags: [] },
        { title: "Pitchers", tags: [] },
        { title: "Little Things", tags: [] },
        { title: "Bhaag Beanie Bhaag", tags: [] },
        { title: "Scam 1992", tags: [] },
        { title: "Better Life Foundation", tags: [] },
        { title: "Bombay Begums", tags: [] },
        { title: "Aspirants", tags: [] },
        { title: "Zindagi Gulzar Hai", tags: [] },
        { title: "Aranyak", tags: [] },
        { title: "Yeh Kaali Kaali Aankhen", tags: [] },
        { title: "Four More shots please", tags: [] },
        { title: "Tabbar", tags: [] },
        { title: "Mai", tags: [] },
        { title: "Fame Game", tags: [] },
        { title: "Hush hush", tags: [] },
        { title: "FLAMES", tags: [] },
        { title: "JL50", tags: [] },
        { title: "IC814", tags: [] },
        { title: "Life hill Gayi", tags: [] },
        { title: "Shekhar Home", tags: [] },
        { title: "Gyarah Gyarah", tags: [] },
        { title: "Black warrant", tags: [] },
        { title: "Dahaad", tags: [] },
        { title: "A Simple Murder", tags: [] },
        { title: "Taaza Khabar", tags: [] },
        { title: "Trial by Fire", tags: [] },
        { title: "Jehanabad", tags: [] },
        { title: "Farzi", tags: ["gem"] },
        { title: "School of Lies", tags: [] },
        { title: "Adhura", tags: [] },
        { title: "Jee Karda", tags: [] },
        { title: "Humans", tags: [] },
        { title: "Criminal Justice", tags: [] },
        { title: "Masoom", tags: [] },
        { title: "Kohraa", tags: [] },
        { title: "The Trial", tags: [] },
        { title: "Kaalkoot", tags: [] },
        { title: "Taali", tags: [] },
        { title: "Aakhri Sach", tags: [] },
        { title: "Charlie Chopra", tags: [] },
        { title: "Killer Soup", tags: [] },
        { title: "Shehar Lakhot", tags: [] },
        { title: "Guns & Gulaabs", tags: [] },
        { title: "Kaala Paani", tags: [] },
        { title: "Class", tags: [] },
        { title: "Karmma Calling", tags: [] },
        { title: "Kumari Srimati", tags: [] },
        { title: "The Night Manager", tags: [] },
        { title: "Guilty Minds", tags: ["gem"] },
        { title: "Scoop", tags: [] },
        { title: "Saas Bahu aur flamingo", tags: [] },
        { title: "Broken News", tags: [] },
        { title: "Murder in Mahim", tags: [] },
        { title: "Jubilee", tags: [] },
        { title: "The Railyway Men", tags: [] },
        { title: "Mamla Legal Hai", tags: [] },
        { title: "Maharani", tags: [] },
        { title: "Mithya", tags: [] },
        { title: "Call me Bae", tags: [] },
        { title: "Raat Jawaan Hai", tags: ["gem"] },
        { title: "Tribhuvan Mishra CA Topper", tags: [] },
        { title: "Dupahiya", tags: [] },
        { title: "Dabba Cartel", tags: [] }
    ]
}
